apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Let it kmow we have a certificate
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - tiagotaquelim.com
        - www.tiagotaquelim.com
      secretName: tiagotaquelim-com
  rules: # All routing rules
    - host: tiagotaquelim.com # PRODUCTION DOMAIN NAME
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-service
              servicePort: 3000
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-service
              servicePort: 3000
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-service
              servicePort: 3000
          - path: /?(.*) # The client service must be the last one!
            backend:
              serviceName: client-service
              servicePort: 3000
    - host: www.tiagotaquelim.com # We need to have it copied to www
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-service
              servicePort: 3000
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-service
              servicePort: 3000
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-service
              servicePort: 3000
          - path: /?(.*) # The client service must be the last one!
            backend:
              serviceName: client-service
              servicePort: 3000
