apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
  labels:
    app: ticketing-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-orders
  template:
    metadata:
      labels:
        app: ticketing-orders
    spec:
      containers:
        - name: orders
          image: cowculator99/ticketing-orders:latest
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: mongodb://orders-mongo-service:27017/orders
            - name: NATS_CLIENT_ID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name # name of the service pod to match nats logs to a running pod
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: ticketing-orders
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
