apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
  labels:
    app: ticketing-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-tickets
  template:
    metadata:
      labels:
        app: ticketing-tickets
    spec:
      containers:
        - name: tickets
          image: cowculator99/ticketing-tickets:latest
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: node-env
                  key: NODE_ENV
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: mongodb://tickets-mongo-service:27017/tickets
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # name of the service pod to match nats logs to a running pod
            - name: NATS_URL
              value: "http://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  selector:
    app: ticketing-tickets
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
