name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-k8s # connects to the cloud provider k8s context
      - run: kubectl apply -f infra/k8s