name: tests-orders

# whenever a pull_request is created/re-opened
on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/orders && npm i && npm run test:ci
